
[kafka_broker]
  address = "kafka:29092"
  cert_path = "not-set"
  cooldown = "1 week"
  enabled = true
  event_filter = "totalRisk &gt;= totalRiskThreshold"
  impact_threshold = 0
  likelihood_threshold = 0
  sasl_mechanism = "PLAIN"
  sasl_password = "not-used"
  sasl_username = "not-used"
  security_protocol = "PLAINTEXT"
  severity_threshold = 0
  tag_filter_enabled = false
  tags = []
  timeout = "60s"
  topic = "platform.notifications.ingress"
  total_risk_threshold = 2

[logging]
  log_level = "info"
  logging_to_cloud_watch_enabled = false

[service_log]
  client_id = "a-service-id"
  client_secret = "a-secret"
  cooldown = "1 week"
  created_by = "service-account-service"
  enabled = false
  event_filter = "totalRisk &gt;= totalRiskThreshold"
  impact_threshold = 0
  likelihood_threshold = 0
  severity_threshold = 0
  tag_filter_enabled = true
  tags = ["osd_customer"]
  timeout = "15s"
  token_url = ""
  total_risk_threshold = 0
  url = "https://api.foobar.com/api/service_logs/v1/"
  username = "service-username"

[storage]
  db_driver = "postgres"
  log_sql_queries = true
  pg_db_name = "notification"
  pg_host = "localhost"
  pg_params = "sslmode=disable"
  pg_password = "postgres"
  pg_port = 5432
  pg_username = "postgres"
